name: soft_shares
description: "A new Flutter project for sharing software."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any
  http:
  path:
  sqflite:
  image_picker:
  intl:
  flutter_localizations:
    sdk: flutter
  firebase_auth:
  google_sign_in:
  firebase_core:
  flutter_facebook_auth:
  url_launcher:
  flutter_rating_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/logo2.svg
    - assets/images/google.svg
    - assets/images/facebook.svg
    - assets/images/Distritos/PT_1.svg
    - assets/images/Distritos/CasteloBranco.svg
    - assets/images/Distritos/Portalegre.svg
    - assets/images/Distritos/Santarem.svg
    - assets/images/Distritos/VilaReal.svg
    - assets/images/Distritos/Viseu.svg
    - assets/images/Distritos/Lisboa.svg
