name: soft_shares
description: "A new Flutter project for sharing software."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/google.svg
    - assets/images/facebook.svg
