// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZvhNRMhNyFn7RaiuuJOhedp28F63LgbM',
    appId: '1:454131677063:web:6e1bd617edde3694c60522',
    messagingSenderId: '454131677063',
    projectId: 'pintlogin',
    authDomain: 'pintlogin.firebaseapp.com',
    storageBucket: 'pintlogin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP0WfRuWA4Dz5h4GrZlVlUjCSXaM8B9k8',
    appId: '1:454131677063:android:53cecb926142572bc60522',
    messagingSenderId: '454131677063',
    projectId: 'pintlogin',
    storageBucket: 'pintlogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIIcq32-ykD6Uny3ZyUz6Z_vF0TyLYHQ4',
    appId: '1:454131677063:ios:68a11129e5f3aa76c60522',
    messagingSenderId: '454131677063',
    projectId: 'pintlogin',
    storageBucket: 'pintlogin.appspot.com',
    androidClientId: '454131677063-vhd6jm175a78lqv24mb8th3u6km1iehe.apps.googleusercontent.com',
    iosClientId: '454131677063-ted69b7b3e99a0d9l2jfsnu2f79f0pkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.softShares',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIIcq32-ykD6Uny3ZyUz6Z_vF0TyLYHQ4',
    appId: '1:454131677063:ios:68a11129e5f3aa76c60522',
    messagingSenderId: '454131677063',
    projectId: 'pintlogin',
    storageBucket: 'pintlogin.appspot.com',
    androidClientId: '454131677063-vhd6jm175a78lqv24mb8th3u6km1iehe.apps.googleusercontent.com',
    iosClientId: '454131677063-ted69b7b3e99a0d9l2jfsnu2f79f0pkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.softShares',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZvhNRMhNyFn7RaiuuJOhedp28F63LgbM',
    appId: '1:454131677063:web:72047cdeb31a1adcc60522',
    messagingSenderId: '454131677063',
    projectId: 'pintlogin',
    authDomain: 'pintlogin.firebaseapp.com',
    storageBucket: 'pintlogin.appspot.com',
  );
}
